name: packages-changed
description: https://github.com/champtitles/action-packages-changed
runs:
  using: "composite"
  steps:
    - id: packages-generator
      run: echo "packages-changed=$({{ github.action_path }}/action.sh)" >> $GITHUB_OUTPUT
      shell: bash
