name: packages-changed
description: https://github.com/champtitles/action-packages-changed
runs:
  using: "composite"
  steps:
    - id: packages-generator
      run: | 
        echo "PACKAGES_CHANGED=$(echo ${{ GITHUB_ACTION_PATH }}/action.sh)" >> $GITHUB_ENV
      shell: bash
