name: packages-changed
description: https://github.com/champtitles/action-packages-changed
outputs:
  packages-changed:
    description: "Packages changed"
    value: ${{ steps.packages-generator.outputs.packages-changed }}
runs:
  using: "composite"
  steps:
    - id: packages-generator
      run: ${{ github.action_path }}/action.sh
      shell: bash
